[build]
  functions = "functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  headers = { "Access-Control-Allow-Origin" = "*", "Access-Control-Allow-Headers" = "*" }
  methods = ["GET", "POST", "PUT", "DELETE"]
